apiVersion: v1
kind: Service
metadata:
  name: websockets
spec:
  ports:
    - port: 6001
      targetPort: 6001
  selector:
    application: websokcets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockets
spec:
  replicas: 1
  selector:
    matchLabels:
      application: websockets
  template:
    metadata:
      labels:
        application: websockets
    spec:
      containers:
        - image: BACKEND_IMAGE
          name: websockets
          cmd: ['/bin/sh', '-c']
          args:
            - "php artisan websockets:serve"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: php-environment

