apiVersion: v1
kind: ConfigMap
metadata:
  name: ######NAMESPACE######php-environment
  labels:
    qaInstance: ######NAMESPACE######
data:
  APP_NAME: LEGENDSPORTS
  APP_ENV: local
  APP_KEY: "base64:we9GwZknrIHsiBOkXBLx4+sNcioxhXuH+zOdl2fHZ+0="
  APP_DEBUG: "true"

  APP_URL: http://######DOMAIN_NAME######
  APP_URL_DOMAIN: ######DOMAIN_NAME######
  BACKSTAGE_URL_SUBDOM: backstage

  LOG_CHANNEL: stack

  DB_CONNECTION: mysql
  DB_HOST: 10.35.48.7
  DB_PORT: "3306"
  DB_DATABASE: ######DATABASE_NAME######

  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: database
  QUEUE_CONNECTION: uniquedbqueue
  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"

  PUSHER_APP_ID: legendsports
  PUSHER_APP_KEY: my-secret-random-key
  PUSHER_APP_SECRET: my-secret-random-secret-key
  PUSHER_APP_CLUSTER: mt1
  PUSHER_HOST: ######NAMESPACE######websockets

  MIX_PUSHER_APP_KEY: my-secret-random-key
  MIX_PUSHER_APP_CLUSTER: mt1

  MAIL_MAILER: smtp
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PORT: 587
  MAIL_USERNAME: apikey
  MAIL_PASSWORD: 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
  MAIL_ENCRYPTION: tls

  LEGENDS_ODDS_URL: https://odds.infra.qa.legendsports.bet/
  LEGENDS_ODDS_TOKEN: Phei0Pie0eiCuZaiBooRahyooJeeJ3oo
