spec:
  rules:
    - host: ######DOMAIN_NAME######
      http:
        paths:
          - backend:
              serviceName: ######NAMESPACE######web
              servicePort: 80
    - host: backstage.######DOMAIN_NAME######
      http:
        paths:
          - backend:
              serviceName: ######NAMESPACE######web
              servicePort: 80
    - host: ws.######DOMAIN_NAME######
      http:
        paths:
          - backend:
              serviceName: ######NAMESPACE######web
              servicePort: 6001
