apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ######NAMESPACE######web
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ######DOMAIN_NAME######
      http:
        paths:
          - backend:
              serviceName: ######NAMESPACE######web
              servicePort: 80
    - host: backstage.######DOMAIN_NAME######
      http:
        paths:
          - backend:
              serviceName: ######NAMESPACE######web
              servicePort: 80
    - host: ws.######DOMAIN_NAME######
      http:
        paths:
          - backend:
              serviceName: ######NAMESPACE######web
              servicePort: 6001
