apiVersion: v1
kind: Service
metadata:
  name: ######NAMESPACE######websockets
  labels:
    qaInstance: ######NAMESPACE######
spec:
  ports:
    - port: 6001
      targetPort: 6001
  selector:
    application: ######NAMESPACE######websockets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ######NAMESPACE######websockets
  labels:
    qaInstance: ######NAMESPACE######
spec:
  replicas: 1
  selector:
    matchLabels:
      application: ######NAMESPACE######websockets
  template:
    metadata:
      labels:
        application: ######NAMESPACE######websockets
        qaInstance: ######NAMESPACE######
    spec:
      containers:
        - image: ######BACKEND_IMAGE######
          name: websockets
          command: ['/bin/sh', '-c']
          args:
            - "php artisan websockets:serve"
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: ######NAMESPACE######php-environment

