apiVersion: apps/v1
kind: Deployment
metadata:
  name: ######NAMESPACE######worker
  labels:
    qaInstance: ######NAMESPACE######
spec:
  replicas: 1
  selector:
    matchLabels:
      application: ######NAMESPACE######worker
  template:
    metadata:
      labels:
        application: ######NAMESPACE######worker
        qaInstance: ######NAMESPACE######
    spec:
      containers:
        - image: ######BACKEND_IMAGE######
          name: worker
          command: ['/bin/sh', '-c']
          args:
            - "php artisan queue:listen"
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: ######NAMESPACE######php-environment
