version: '2'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        links:
            - app

    app:
        build:
            context: ./docker
            dockerfile: app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

    websockets:
        build:
            context: ./docker
            dockerfile: websockets.docker
        volumes:
          - ./:/var/www
        ports:
          - "6001:6001"
        links:
          - database
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=database"

    scheduler:
        build:
            context: ./docker
            dockerfile: scheduler.docker
        volumes:
          - ./:/var/www
        links:
          - database
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=database"

    database:
        image: mysql:8
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=legendsports"
