apiVersion: v1
kind: ConfigMap
metadata:
  name: php-environment
data:
  APP_NAME: LEGENDSPORTS
  APP_ENV: local
  APP_KEY: "base64:we9GwZknrIHsiBOkXBLx4+sNcioxhXuH+zOdl2fHZ+0="
  APP_DEBUG: "true"

  APP_URL: http://staging.legendsbet.com
  APP_URL_DOMAIN: staging.legendsbet.com
  BACKSTAGE_URL_SUBDOM: backstage

  LOG_CHANNEL: stack

  DB_CONNECTION: mysql
  DB_HOST: 10.35.48.7
  DB_PORT: "3306"
  DB_DATABASE: legendsports-staging

  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: database
  QUEUE_CONNECTION: uniquedbqueue
  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"

  PUSHER_APP_ID: legendsports
  PUSHER_APP_KEY: my-secret-random-key
  PUSHER_APP_SECRET: my-secret-random-secret-key
  PUSHER_APP_CLUSTER: mt1

  MIX_PUSHER_APP_KEY: my-secret-random-key
  MIX_PUSHER_APP_CLUSTER: mt1

  LEGENDS_ODDS_URL: https://odds.infra.qa.legendsports.bet/
  LEGENDS_ODDS_TOKEN: f3jzHublrmqBbqVz23wNlhBpLMUTxw

