apiVersion: v1
kind: ConfigMap
metadata:
  name: php-environment
data:
  APP_NAME: LEGENDSPORTS
  APP_ENV: local
  APP_KEY: "base64:we9GwZknrIHsiBOkXBLx4+sNcioxhXuH+zOdl2fHZ+0="
  APP_DEBUG: "true"

  APP_URL: http://staging.legendsports.bet
  APP_URL_DOMAIN: staging.legendsports.bet
  BACKSTAGE_URL_SUBDOM: backstage

  LOG_CHANNEL: stack

  DB_CONNECTION: mysql
  DB_HOST: 10.35.48.3
  DB_PORT: "3306"
  DB_DATABASE: legendsports-staging

  BROADCAST_DRIVER: pusher
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"

  PUSHER_APP_ID: legendsports
  PUSHER_APP_KEY: my-secret-random-key
  PUSHER_APP_SECRET: my-secret-random-secret-key
  PUSHER_APP_CLUSTER: mt1

  MIX_PUSHER_APP_KEY: my-secret-random-key
  MIX_PUSHER_APP_CLUSTER: mt1

  JSONODDS_API_KEY: 3b279a7d-7d95-4eda-89cb-3c1f96093fc6
  BETS365_TOKEN: 44933-Ygmt1mvQIl8hzp

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - staging.legendsports.bet
        - backstage.staging.legendsports.bet
      secretName: web-tls
  rules:
    - host: staging.legendsports.bet
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 80
    - host: backstage.staging.legendsports.bet
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: websockets
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
    - hosts:
        - ws.staging.legendsports.bet
      secretName: websocket-tls
  rules:
    - host: ws.staging.legendsports.bet
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 6001
