apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scheduler
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 30
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: scheduler
              image: ######BACKEND_IMAGE######
              command: ['/bin/sh', '-c']
              args:
              - "php artisan schedule:run --verbose --no-interaction"
              imagePullPolicy: Always
              env:
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: password
              envFrom:
                - configMapRef:
                    name: php-environment
