<?php

namespace DoctrineProxies\__CG__\App\Domain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TournamentEvent extends \App\Domain\TournamentEvent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'id', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'createdAt', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'updatedAt', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'apiEvent', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'tournament', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'bets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'id', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'createdAt', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'updatedAt', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'apiEvent', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'tournament', '' . "\0" . 'App\\Domain\\TournamentEvent' . "\0" . 'bets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TournamentEvent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getApiEvent(): \App\Domain\ApiEvent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiEvent', []);

        return parent::getApiEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function getTournament(): \App\Domain\Tournament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTournament', []);

        return parent::getTournament();
    }

    /**
     * {@inheritDoc}
     */
    public function getBets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBets', []);

        return parent::getBets();
    }

    /**
     * {@inheritDoc}
     */
    public function evaluate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'evaluate', []);

        parent::evaluate();
    }

    /**
     * {@inheritDoc}
     */
    public function canBetBePlaced(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canBetBePlaced', []);

        return parent::canBetBePlaced();
    }

}
